# Part 3 API -- Team Stress Insight Tool.
#
# ALL DATA SERVED BY THIS API IS SIMULATED. Nothing here touches a real
# calendar, a real person, or a real wearable. The fixtures are generated by
# part3/contracts/make_fixtures.py.
#
# Privacy split:
#   /employee/{id}      -> PRIVATE, per-person. Part 5 shows a person only
#                          their own record.
#   /team/correlations  -> person-free aggregate, GATED at k>=5 by default.
#                          Add ?raw=true for ungated counts (Part 4's input).
#                          Safe by default: 8 of 9 patterns on the real data
#                          covered a single person, so an ungated default would
#                          have shipped a k=1 employer view.
#
# Run:  uvicorn api.main:app --reload --port 8000 --app-dir part3

from __future__ import annotations

import json
import sys
import traceback
from pathlib import Path
from typing import Any

# --- make part3/src importable no matter what the cwd is -------------------
_API_DIR = Path(__file__).resolve().parent          # <repo>/part3/api
PART3_DIR = _API_DIR.parent                         # <repo>/part3
REPO_ROOT = PART3_DIR.parent                        # <repo>
SRC_DIR = PART3_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))
# ---------------------------------------------------------------------------

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

FIXTURES_DIR = PART3_DIR / "data" / "fixtures"
OUT_DIR = PART3_DIR / "data" / "out"
STRESS_CSV = FIXTURES_DIR / "stress_scores.csv"
MEETINGS_JSON = FIXTURES_DIR / "meeting_features.json"
EMPLOYEE_JSON = OUT_DIR / "employee_insight.json"
TEAM_JSON = OUT_DIR / "team_correlations.json"
RAW_TEAM_JSON = OUT_DIR / "team_correlations_raw.json"

app = FastAPI(
    title="Part 3 -- Correlation & Insight Engine (SIMULATED DATA)",
    description=(
        "LLM agents propose, Python proves. All data is synthetic. "
        "employee_insight.json is private/per-person. team_correlations.json "
        "carries no person_id and is GATED at k>=5 by default; add ?raw=true "
        "for ungated counts, which is Part 4's input. Part 4 owns the "
        "authoritative policy -- the gate here is a safe default."
    ),
    version="0.1.0",
)

# Permissive on purpose: Part 5's UI may be served from anywhere during the demo.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


class AnalyzeRequest(BaseModel):
    offline: bool = False
    limit: int | None = None


def _read_json(path: Path) -> Any:
    if not path.exists():
        raise HTTPException(
            status_code=409,
            detail=(
                f"{path.name} does not exist yet at {path}. "
                "POST /analyze first to run the pipeline."
            ),
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:  # corrupt/partial write
        raise HTTPException(
            status_code=500, detail=f"{path.name} is not valid JSON: {exc}"
        ) from exc


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "data_provenance": "SIMULATED"}


@app.post("/analyze")
def analyze(req: AnalyzeRequest | None = None) -> dict[str, Any]:
    """Run the full pipeline over the fixtures and write both output files."""
    req = req or AnalyzeRequest()
    try:
        # Lazy import: the orchestrator is owned by another dev and may not
        # exist yet. This module must still import cleanly without it.
        from insight.pipeline import run_pipeline

        summary = run_pipeline(
            stress_csv=STRESS_CSV,
            meetings_json=MEETINGS_JSON,
            out_dir=OUT_DIR,
            offline=req.offline,
            limit=req.limit,
        )
        return {"status": "ok", "data_provenance": "SIMULATED", **dict(summary)}
    except Exception as exc:  # hackathon demo: show the error, don't hide it
        raise HTTPException(
            status_code=500,
            detail={
                "error": f"{type(exc).__name__}: {exc}",
                "traceback": traceback.format_exc(limit=12),
            },
        ) from exc


@app.get("/people")
def people() -> dict[str, Any]:
    """Person ids present in the last run (helps Part 5 build a picker)."""
    doc = _read_json(EMPLOYEE_JSON)
    ids = sorted((doc.get("people") or {}).keys())
    return {"count": len(ids), "people": ids, "data_provenance": "SIMULATED"}


@app.get("/employee/{person_id}")
def employee(person_id: str) -> dict[str, Any]:
    """PRIVATE per-person insight."""
    doc = _read_json(EMPLOYEE_JSON)
    record = (doc.get("people") or {}).get(person_id)
    if record is None:
        raise HTTPException(
            status_code=404, detail=f"No insight for person_id '{person_id}'."
        )
    return record


@app.get("/team/correlations")
def team_correlations(raw: bool = False) -> dict[str, Any]:
    """Person-free team aggregate.

    Default is GATED at k>=5: patterns covering fewer than five distinct people
    are withheld, and the count withheld is reported rather than hidden.

    `?raw=true` returns ungated counts. That is Part 4's input -- it needs the
    honest numbers to apply the authoritative policy -- but it must be asked
    for explicitly so that no employer-facing surface gets it by accident.
    """
    if raw:
        payload = _read_json(RAW_TEAM_JSON)
        payload["warning"] = (
            "UNGATED: includes patterns covering fewer than k people. "
            "Do not render this in an employer view without applying the gate."
        )
        return payload
    return _read_json(TEAM_JSON)
