/* AUTO-GENERATED by ui/build-fallback.mjs — do not edit by hand.
   Mirror of data/*.json, inlined so index.html works over file:// too. */
window.FALLBACK = {
  employee: {
  "schema_version": "1.0",
  "_comment": "SYNTHETIC DATA. Part 3 -> Part 5 contract. No real person is represented here. Replace this file with the real Part 3 output; keep the key names identical.",
  "synthetic": true,
  "person_id": "EMP-0417",
  "display_name": "You",
  "generated_at": "2026-09-16",
  "current": {
    "stress_score": 78,
    "band": "Elevated",
    "baseline_14d": 56,
    "delta_vs_baseline": 22
  },
  "biometrics_today": [
    {
      "label": "Recovery",
      "value": 41,
      "unit": "%",
      "baseline": 63,
      "direction": "lower_is_worse"
    },
    {
      "label": "HRV",
      "value": 38,
      "unit": "ms",
      "baseline": 49,
      "direction": "lower_is_worse"
    },
    {
      "label": "Sleep",
      "value": 6.1,
      "unit": "h",
      "baseline": 7.9,
      "direction": "lower_is_worse"
    },
    {
      "label": "Resting HR",
      "value": 62,
      "unit": "bpm",
      "baseline": 55,
      "direction": "higher_is_worse"
    },
    {
      "label": "Day strain",
      "value": 14.2,
      "unit": "",
      "baseline": 11.4,
      "direction": "higher_is_worse"
    }
  ],
  "trend": [
    {
      "date": "2026-09-03",
      "weekday": "Thu",
      "stress_score": 66,
      "meetings": 5
    },
    {
      "date": "2026-09-04",
      "weekday": "Fri",
      "stress_score": 54,
      "meetings": 2
    },
    {
      "date": "2026-09-05",
      "weekday": "Sat",
      "stress_score": 39,
      "meetings": 0
    },
    {
      "date": "2026-09-06",
      "weekday": "Sun",
      "stress_score": 35,
      "meetings": 0
    },
    {
      "date": "2026-09-07",
      "weekday": "Mon",
      "stress_score": 51,
      "meetings": 3
    },
    {
      "date": "2026-09-08",
      "weekday": "Tue",
      "stress_score": 62,
      "meetings": 4
    },
    {
      "date": "2026-09-09",
      "weekday": "Wed",
      "stress_score": 79,
      "meetings": 6
    },
    {
      "date": "2026-09-10",
      "weekday": "Thu",
      "stress_score": 72,
      "meetings": 5
    },
    {
      "date": "2026-09-11",
      "weekday": "Fri",
      "stress_score": 56,
      "meetings": 2
    },
    {
      "date": "2026-09-12",
      "weekday": "Sat",
      "stress_score": 40,
      "meetings": 0
    },
    {
      "date": "2026-09-13",
      "weekday": "Sun",
      "stress_score": 37,
      "meetings": 0
    },
    {
      "date": "2026-09-14",
      "weekday": "Mon",
      "stress_score": 55,
      "meetings": 4
    },
    {
      "date": "2026-09-15",
      "weekday": "Tue",
      "stress_score": 64,
      "meetings": 4
    },
    {
      "date": "2026-09-16",
      "weekday": "Wed",
      "stress_score": 78,
      "meetings": 7
    }
  ],
  "insight": {
    "headline": "Your stress spikes on days with 4+ meetings and no gap longer than 15 minutes — most reliably on Wednesdays.",
    "detail": "The pattern is calendar-shaped, not workload-shaped. Days with the same number of working hours but one protected midday block land 27 points lower.",
    "confidence": "Moderate",
    "confidence_note": "n = 14 days of synthetic data. Not a clinical finding.",
    "evidence": [
      "Both 14-day stress peaks (Sep 9, Sep 16) fell on a Wednesday with 6+ meetings.",
      "Days with a ≥45 min midday buffer averaged 47; days without averaged 74.",
      "HRV fell 22% on your two highest meeting-density days.",
      "Meeting density → same-day stress correlation: r = 0.71."
    ]
  },
  "contributing_factors": [
    {
      "factor": "Back-to-back meeting blocks",
      "weight_pct": 32,
      "note": "6 of 7 meetings today had no gap before the next."
    },
    {
      "factor": "No recovery buffer",
      "weight_pct": 24,
      "note": "Median gap between meetings: 5 min."
    },
    {
      "factor": "Sleep debt",
      "weight_pct": 19,
      "note": "1.8 h below your 30-day baseline."
    },
    {
      "factor": "After-hours invites",
      "weight_pct": 14,
      "note": "2 invites landed after 18:00 local."
    },
    {
      "factor": "Low HRV carryover",
      "weight_pct": 11,
      "note": "Third consecutive day below baseline."
    }
  ],
  "opt_in": {
    "enabled": false,
    "shares_if_enabled": [
      "That your calendar shows a back-to-back density pattern",
      "The recommended calendar change (no-meeting block)"
    ],
    "never_shares": [
      "Your stress score, in any form",
      "Your biometrics",
      "Your name attached to any figure above"
    ]
  }
},
  employer: {
  "schema_version": "1.0",
  "_comment": "SYNTHETIC DATA. Part 4 -> Part 5 contract. Non-personal by construction: category + coarse severity band + recommended action only. No scores, no IDs, no per-person rows. Replace with the real Part 4 output; keep key names identical.",
  "synthetic": true,
  "team_id": "TEAM-NORTH",
  "team_label": "Platform — North",
  "generated_at": "2026-09-16",
  "k_anonymity": {
    "threshold": 5,
    "team_size": 9,
    "satisfied": true
  },
  "structural_summary": {
    "hero": {
      "label": "Meetings per person on Wednesdays",
      "value": 5.2,
      "unit": ""
    },
    "tiles": [
      {
        "label": "Meetings / person / week",
        "value": 21.4,
        "unit": ""
      },
      {
        "label": "Recurring meetings with no agenda",
        "value": 41,
        "unit": "%"
      },
      {
        "label": "Invites sent outside 09:00–18:00",
        "value": 18,
        "unit": "%"
      },
      {
        "label": "Median gap between meetings",
        "value": 10,
        "unit": "min"
      }
    ]
  },
  "meeting_density": {
    "caption": "Team average meetings per person, by weekday and time block.",
    "days": [
      "Mon",
      "Tue",
      "Wed",
      "Thu",
      "Fri"
    ],
    "blocks": [
      "08–10",
      "10–12",
      "12–14",
      "14–16",
      "16–18"
    ],
    "grid": [
      [
        0.4,
        1.2,
        0.6,
        1.1,
        0.5
      ],
      [
        0.6,
        1.5,
        0.8,
        1.3,
        0.7
      ],
      [
        1.1,
        2.3,
        1.4,
        2.1,
        1.2
      ],
      [
        0.7,
        1.6,
        0.9,
        1.4,
        0.8
      ],
      [
        0.5,
        1,
        0.4,
        0.8,
        0.9
      ]
    ]
  },
  "causal_categories": [
    {
      "category": "Meeting density",
      "structural_fact": "Wednesdays average 5.2 meetings per person, with no scheduled gap over 30 minutes.",
      "severity_band": "High",
      "trend": "up",
      "recommended_action": "Declare a protected 2-hour no-meeting block on Wednesday mornings for the whole team."
    },
    {
      "category": "Recovery buffer",
      "structural_fact": "The median gap between consecutive meetings across the team is 10 minutes.",
      "severity_band": "High",
      "trend": "flat",
      "recommended_action": "Change the calendar default to 25- and 50-minute meetings so a buffer exists by default."
    },
    {
      "category": "Agenda hygiene",
      "structural_fact": "41% of recurring meetings have no agenda attached at send time.",
      "severity_band": "Elevated",
      "trend": "up",
      "recommended_action": "Require an agenda field on recurring invites; auto-cancel any recurring meeting with no agenda for three cycles."
    },
    {
      "category": "Workload distribution",
      "structural_fact": "Meeting load between the lightest and heaviest quartile of the team differs by 2.3×.",
      "severity_band": "Elevated",
      "trend": "up",
      "recommended_action": "Run a workload rebalancing check-in at this week's team sync — with the whole team, not selected individuals."
    },
    {
      "category": "After-hours load",
      "structural_fact": "18% of invites are sent outside 09:00–18:00 local time.",
      "severity_band": "Moderate",
      "trend": "flat",
      "recommended_action": "Turn on delayed-send defaults for invites composed after 18:00."
    },
    {
      "category": "Focus fragmentation",
      "structural_fact": "The longest uninterrupted block on a median day is 47 minutes.",
      "severity_band": "Low",
      "trend": "down",
      "recommended_action": "No action needed this cycle — continue monitoring."
    }
  ],
  "opt_in_shares": {
    "count": 2,
    "min_reportable": 3,
    "reportable": false,
    "suppressed_message": "2 people opted to share specifics. Below the reporting floor of 3, so their content is withheld."
  },
  "never_shown": [
    "Any individual's stress score",
    "Any name, employee ID, or re-identifiable attribute",
    "Any per-person biometric reading",
    "Counts of affected people below the k-anonymity threshold",
    "Any ranking or comparison of team members"
  ]
}
};
